import assert from 'node:assert/strict'
import { symlinkSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { test } from 'node:test'
import { listDisplayFiles, readDisplayFile } from '../src/explorer.ts'
import { OhMyMemoStore } from '../src/store.ts'
import { rebuildViews } from '../src/views.ts'
import { scratchRoot } from './helpers/scratch.ts'

async function fixture(): Promise<{ root: string; store: OhMyMemoStore; normalPath: string; sensitivePath: string }> {
  const root = scratchRoot()
  const store = new OhMyMemoStore({ root, watch: false })
  await store.open()
  const normal = await store.create({
    content: '# Package manager\n\nUse pnpm.',
    kind: 'semantic',
    scope: 'user',
    key: 'preference.package-manager',
    pinned: true,
  })
  const sensitive = await store.create({
    content: 'A private, non-credential health note.',
    kind: 'semantic',
    scope: 'user',
    key: 'profile.health-note',
    privacy: 'sensitive',
  })
  await store.createCandidate({
    content: 'Candidate body.',
    kind: 'semantic',
    scope: 'user',
    key: 'dream.candidate',
    confirmed: false,
    reason: 'test inference',
  })
  await rebuildViews(store.root, store.catalog, store.storeConfig, new Date().toISOString())
  return { root, store, normalPath: normal.path, sensitivePath: sensitive.path }
}

test('display index includes only current generated Markdown views and no internals', async () => {
  const { root, store } = await fixture()
  writeFileSync(join(root, 'views', 'untrusted.md'), '# not generated by OhMyMemo')
  const tree = listDisplayFiles(root, store.catalog, 100, 16_384)
  assert.ok(tree.files.some(file => file.path.startsWith('scopes/user/')))
  assert.ok(tree.files.some(file => file.path.startsWith('inbox/candidates/')))
  assert.ok(tree.files.some(file => file.path === 'views/user-profile.md'))
  assert.ok(tree.files.every(file => file.path !== 'views/untrusted.md'))
  assert.ok(tree.files.every(file => !file.path.includes('journal') && !file.path.includes('.state')))
  assert.ok(tree.files.every(file => file.path !== 'config.yaml' && file.path !== 'manifest.yaml'))
  const pinned = store.catalog.allEntries().find(entry => entry.record.key === 'preference.package-manager')
  assert.ok(pinned !== undefined)
  await store.forget({ id: pinned.record.id, reason: 'verify stale generated view exclusion' })
  const afterForget = listDisplayFiles(root, store.catalog, 100, 16_384)
  assert.ok(afterForget.files.every(file => file.path !== 'views/user-profile.md'))
  store.close()
})

test('display reads parse record bodies Host-side and redact sensitive Markdown', async () => {
  const { root, store, normalPath, sensitivePath } = await fixture()
  const tree = listDisplayFiles(root, store.catalog, 100, 16_384)
  const normal = readDisplayFile(root, store.catalog, { path: normalPath, generation: tree.generation }, { maxFiles: 100, maxBytes: 16_384 })
  assert.equal(normal.markdown, '# Package manager\n\nUse pnpm.')
  assert.equal(normal.redacted, false)
  assert.equal(normal.meta.status, 'active')
  const sensitive = readDisplayFile(root, store.catalog, { path: sensitivePath, generation: tree.generation }, { maxFiles: 100, maxBytes: 16_384 })
  assert.equal(sensitive.markdown, '')
  assert.equal(sensitive.redacted, true)
  const view = readDisplayFile(root, store.catalog, { path: 'views/user-profile.md', generation: tree.generation }, { maxFiles: 100, maxBytes: 16_384 })
  assert.match(view.markdown, /^# User profile/u)
  assert.equal(view.markdown.includes('generated: true'), false)
  store.close()
})

test('display reads reject stale generations, traversal, oversized files and symlink escapes', async () => {
  const { root, store, normalPath } = await fixture()
  const tree = listDisplayFiles(root, store.catalog, 100, 16_384)
  assert.throws(
    () => readDisplayFile(root, store.catalog, { path: normalPath, generation: 'sha256:stale' }, { maxFiles: 100, maxBytes: 16_384 }),
    (error: unknown) => (error as { code?: string }).code === 'OHMYMEMO_TREE_STALE',
  )
  assert.throws(
    () => readDisplayFile(root, store.catalog, { path: '../config.yaml', generation: tree.generation }, { maxFiles: 100, maxBytes: 16_384 }),
    (error: unknown) => (error as { code?: string }).code === 'OHMYMEMO_BAD_REQUEST',
  )
  const tinyTree = listDisplayFiles(root, store.catalog, 100, 1)
  assert.throws(
    () => readDisplayFile(root, store.catalog, { path: normalPath, generation: tinyTree.generation }, { maxFiles: 100, maxBytes: 1 }),
    (error: unknown) => (error as { code?: string }).code === 'OHMYMEMO_FILE_TOO_LARGE',
  )
  writeFileSync(join(root, ...normalPath.split('/')), 'changed after the tree snapshot')
  assert.throws(
    () => readDisplayFile(root, store.catalog, { path: normalPath, generation: tree.generation }, { maxFiles: 100, maxBytes: 16_384 }),
    (error: unknown) => (error as { code?: string }).code === 'OHMYMEMO_TREE_STALE',
  )

  const outside = join(root, '..', 'outside.md')
  writeFileSync(outside, 'outside')
  symlinkSync(outside, join(root, 'views', 'outside.md'))
  const refreshed = listDisplayFiles(root, store.catalog, 100, 16_384)
  assert.ok(refreshed.files.every(file => file.path !== 'views/outside.md'))
  store.close()
})
